default: &default
  adapter: postgresql
  encoding: unicode
  username: jaaystones1
  password: jogolo
  host: localhost

development:
  <<: *default
  database: spacesheep_development

test:
  <<: *default
  database: spacesheep_test

production:
  <<: *default
  database: spacesheep_production
